### ISSUE TITLE
Body doesn't cover whole screen on some mobile views

### ISSUE THREAD

**Issue by AmanGotchu** [tamuhack-org/gobble#39]
<img width="405" alt="screen shot 2018-08-29 at 11 22 15 am" src="https://user-images.githubusercontent.com/14339863/44801273-3b110400-ab7e-11e8-9098-ecaa8a8ac8d6.png">

This is for Galaxy S5

**Comment by jay-khatri** [comment]
@AmanGotchu can we deal with this when we add a second page? Unless you know the fix...

**Comment by AmanGotchu** [comment]
Yeah no problem, just wanted to address it.

**Comment by AmanGotchu** [comment]
The problem is your bitmoji lmao. It's messing up the position of the screen.
