### ISSUE TITLE
fix about text grammar

### ISSUE THREAD

**Issue by gracekfan** [tamuhack-org/gobble#80]
change "You'll have the freedom to create a product, learn the new skills or just have fun working on a project with friends"

to 
"You'll have the freedom to create a product, learn new skills or just have fun working on a project with friends"

**Comment by salman0907** [comment]
We should mention why people would want to be their resumes. We kind of mention it randomly at the end of the paragraph. Maybe change:

We'll also provide all the free food and free swag—just be sure to bring plenty of resumes!
to
We'll also provide all the free food and free swag—just be sure to bring plenty of resumes for all of the awesome sponsors and mentors you'll meet! Check them out below!

**Comment by muinmomin** [comment]
fixed both.
