### ISSUE TITLE
minor ui tweaks

### ISSUE THREAD

**Issue by gracekfan** [tamuhack-org/gobble#81]
- [x]  1. Make margin/padding between nav-bar and titles (about, sponsors, etc) the same height
- [x]  3. Increase space between end of content and footer (40px)
- [x]  4. Mobile-view: fix padding issue between content and graphics
- [x]  5. Decrease margin between about and "hack" in hackathon... by 10-20px
- [x]  7. Decrease padding in footer
- [x]  8. Increase Copyright text by 2px
- [x]  9. Change bitmoji images to updated bitmoji image
- [x] 10. Decrease size of mlh banner
- [x] 11. Get rid of contact in nav-bar + add email info in footer

**Comment by muinmomin** [comment]
Fixed 3.

**Comment by muinmomin** [comment]
@gracekfan can you expand on (7) and (4)?

I think 4 might be fixed.

**Comment by gracekfan** [comment]
@muinmomin 4 is between the reveille and the text, and the bitmojis and text, where there's just a massive gap because we padded the images

7 is i just want the footer to be thinner

**Comment by mkchoi212** [comment]
#112 addresses 8

**Comment by mkchoi212** [comment]
skurt
