### ISSUE TITLE
FAQ page fixes

### ISSUE THREAD

**Issue by gracekfan** [tamuhack-org/gobble#86]
- [x] when you click on faq in the nav-bar, page doesn't extend far enough
<img width="1440" alt="screen shot 2018-09-05 at 9 08 55 am" src="https://user-images.githubusercontent.com/33182506/45098839-774ae400-b0eb-11e8-87ca-72ae3091214a.png">

- [ ] animate the faq (swipe/slide up motion)
- [x] i have a specific style i want for the note in the first question but put it in a separate paragraph for now
- [x] reduce column width of question title + text by 1/3rd
- [ ] bold/highlight the question in the sidebar that they're currently viewing
- [x] link mlh code of conduct
- [x] faq should be same size as sponsors and about (this one i'm just eyeballing, if they're the same that's great)
- [x] indent the faq sidebar more so that it aligns with the paragraphs in about
- [ ] can we have the hover fade in? or like in ideo swipe across the full block
- [ ] align faq title with top of questions list

**Comment by gracekfan** [comment]
- [ ] add fb to sponsor document

**Comment by jay-khatri** [comment]
@gracekfan what still needs to be done for this? Can we create a new issue with an updates list?

**Comment by gracekfan** [comment]
see #145
