### ISSUE TITLE
make colors file

### ISSUE THREAD

**Issue by suvedhs** [tamuhack-org/gobble#9]
instead of looking up the hex code for a color that will be used several times, we should have a separate stylesheet with all the colors defined globally and imported into other stylesheets

**Comment by jay-khatri** [comment]
Good idea. I'm thinking we have some sort of `constants.js` file that we import from in any file that looks like `**Styles.js`.

**Comment by muinmomin** [comment]
@suvedhs inactive for now. ![bitmoji](https://render.bitstrips.com/v2/cpanel/618b2117-3a34-4a18-b5ab-90992aae714a-8aee217f-a83b-43ee-a322-38e25b6e6d78-v1.png?transparent=1&palette=1&width=246)
